---
swagger: "2.0"
info:
  title: "Weather Provider API"
  version: "1.0.0"
  x-ibm-name: "weather-provider-api"
host: "myweatherprovider.mybluemix.net"
schemes:
- "https"
basePath: "/"
produces:
- "application/json"
paths:
  /current:
    get:
      summary: "Current Weather"
      parameters:
      - name: "zipcode"
        in: "query"
        description: "A valid 5-digit US zip code"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Current"
  /today:
    get:
      summary: "Today's Weather"
      parameters:
      - name: "zipcode"
        in: "query"
        description: "A valid 5-digit US zip code"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/Today"
definitions:
  Today:
    type: "object"
    properties:
      zip:
        type: "string"
      hi:
        type: "integer"
      lo:
        type: "integer"
      nightHumidity:
        type: "integer"
      city:
        type: "string"
      state:
        type: "string"
      dayHumidity:
        type: "integer"
  Current:
    type: "object"
    properties:
      zip:
        type: "string"
      temperature:
        type: "integer"
      humidity:
        type: "integer"
      city:
        type: "string"
      state:
        type: "string"
x-ibm-configuration:
  enforced: true
  testable: true
  phase: "realized"
  cors:
    enabled: true
consumes:
- "application/json"
